# Generated by Django 6.0.1 on 2026-02-14 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_delete_loginuser_delete_signupuser_todolist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todoitem',
            constraint=models.UniqueConstraint(fields=('todo_list', 'title'), name='unique_item_per_list'),
        ),
        migrations.AddConstraint(
            model_name='todolist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_todolist_per_user'),
        ),
    ]
